name: CI
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']
  workflow_dispatch:
jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.10']
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        run: |
          pip install pytest
          pytest ./src/internal/controller ./src/internal/models ./src/internal/objects ./src/internal/repositories ./src/internal/storages ./src/internal/pub_sub ./src/tests --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
      - name: Lint with Ruff
        run: |
          pip install ruff  
          ruff check --output-format=github .
